/**
 * The wire between a web page and this extension, and the rules that make it
 * safe to answer.
 *
 * This file is deliberately pure: no `chrome`, no DOM, no wallet. Everything
 * that decides *whether* a request is allowed lives here so it can be tested
 * directly, because the parts that cannot be tested directly — a content
 * script, a service worker, a window — are exactly the parts where a mistake
 * is invisible until someone loses money.
 *
 * ## Origin is taken from the messenger, never from the message
 *
 * A page can put any string in a message it sends. It cannot forge the origin
 * the browser attaches to the sender of a `chrome.runtime` message. So the
 * request type below has **no origin field at all** — not an ignored one, not
 * an optional one. There is nothing for a caller to set, so there is nothing
 * for a reviewer to check, and a future edit that adds one has to explain
 * itself in a diff.
 *
 * ## Three tiers, deny-by-default
 *
 * - **Open**: answerable to anyone. Only `isEnabled`, and only because its
 *   answer ("have you already granted this site?") is something the site can
 *   determine anyway by calling `enable` and seeing what happens.
 * - **Granted**: needs a standing grant for this origin. Every read.
 * - **Per-use**: needs a standing grant *and* a fresh human approval for this
 *   exact request. Everything that signs or broadcasts. A cached approval for
 *   signing would mean a site that got one "yes" can spend forever.
 *
 * Anything not named is refused. A deny-list would be wrong the day CIP-30
 * gains a method, and the failure would be open rather than closed.
 */

/** Methods this provider answers. Deny-by-default: absent means refused. */
export const OPEN_METHODS = ["isEnabled"] as const;

export const GRANTED_METHODS = [
  "getNetworkId",
  "getUtxos",
  "getCollateral",
  "getBalance",
  "getUsedAddresses",
  "getUnusedAddresses",
  "getChangeAddress",
  "getRewardAddresses",
  "getExtensions",
] as const;

/**
 * Signing and broadcasting. Approved one request at a time, never remembered.
 *
 * `submitTx` is here and not under `GRANTED_METHODS` on purpose: a site can
 * hand over bytes this wallet never signed, and putting them on the network
 * under the user's connection is still an action taken on the user's behalf.
 */
export const PER_USE_METHODS = ["signTx", "signData", "submitTx"] as const;

/**
 * The CIP-30 methods a wallet must have to be usable at all.
 *
 * Named here, in the file both sides already import, because this is a contract
 * between two files that never call each other: `inpage/provider.ts` builds the
 * object a dApp receives, and `src/lib/cardano/cip30.ts` decides whether an
 * injected wallet is complete enough to connect to. Phoenix's web build runs
 * that second check against Phoenix's own extension — so a method dropped from
 * the provider makes this wallet reject itself, with a message about the
 * *user's* wallet being unusable. Keeping the list in one place is what lets a
 * test catch that instead of a user.
 */
export const CIP30_MANDATORY_METHODS = [
  "getNetworkId",
  "getUtxos",
  "getBalance",
  "getUsedAddresses",
  "getUnusedAddresses",
  "getChangeAddress",
  "getRewardAddresses",
  "signTx",
  "signData",
  "submitTx",
] as const;

export const ENABLE_METHOD = "enable" as const;

export type OpenMethod = (typeof OPEN_METHODS)[number];
export type GrantedMethod = (typeof GRANTED_METHODS)[number];
export type PerUseMethod = (typeof PER_USE_METHODS)[number];
export type Method = OpenMethod | GrantedMethod | PerUseMethod | typeof ENABLE_METHOD;

const OPEN = new Set<string>(OPEN_METHODS);
const GRANTED = new Set<string>(GRANTED_METHODS);
const PER_USE = new Set<string>(PER_USE_METHODS);

export function isKnownMethod(m: string): m is Method {
  return m === ENABLE_METHOD || OPEN.has(m) || GRANTED.has(m) || PER_USE.has(m);
}

/** What a method needs before it may run. */
export type Requirement = "open" | "grant" | "approval" | "enable" | "refused";

export function requirementOf(method: string): Requirement {
  if (method === ENABLE_METHOD) return "enable";
  if (OPEN.has(method)) return "open";
  if (GRANTED.has(method)) return "grant";
  if (PER_USE.has(method)) return "approval";
  return "refused";
}

// ─── Envelopes ────────────────────────────────────────────────────────────────

/** Tags every message so unrelated `postMessage` traffic is ignored cheaply. */
export const CHANNEL = "phoenix-cip30";

export type Request = {
  channel: typeof CHANNEL;
  kind: "req";
  /** Correlates the answer. Opaque to us; generated by the page side. */
  id: string;
  method: string;
  params: unknown[];
};

export type Response =
  | { channel: typeof CHANNEL; kind: "res"; id: string; ok: true; value: unknown }
  | { channel: typeof CHANNEL; kind: "res"; id: string; ok: false; error: ApiError };

/** CIP-30's error shape. `code` is the number the spec defines; `info` is prose. */
export type ApiError = { code: number; info: string };

/** CIP-30 `APIError` codes. */
export const API_ERROR = {
  InvalidRequest: -1,
  InternalError: -2,
  Refused: -3,
  AccountChange: -4,
} as const;

/** CIP-30 `TxSignError` codes. */
export const TX_SIGN_ERROR = { ProofGeneration: 1, UserDeclined: 2 } as const;

/** CIP-30 `TxSendError` codes. */
export const TX_SEND_ERROR = { Refused: 1, Failure: 2 } as const;

export const refused = (info: string): ApiError => ({ code: API_ERROR.Refused, info });
export const invalid = (info: string): ApiError => ({ code: API_ERROR.InvalidRequest, info });
export const internal = (info: string): ApiError => ({ code: API_ERROR.InternalError, info });
export const declined = (info: string): ApiError => ({ code: TX_SIGN_ERROR.UserDeclined, info });

/**
 * Recognise a request without trusting it.
 *
 * Called on `window.postMessage` data, which is anything at all — another
 * extension's traffic, a library's own bus, or a page deliberately probing for
 * a shape that gets past this. So every field is checked, `params` must really
 * be an array, and nothing is coerced: a request that is not exactly right is
 * not a request.
 */
export function parseRequest(data: unknown): Request | null {
  if (!data || typeof data !== "object") return null;
  const d = data as Record<string, unknown>;
  if (d.channel !== CHANNEL || d.kind !== "req") return null;
  if (typeof d.id !== "string" || d.id.length === 0 || d.id.length > 128) return null;
  if (typeof d.method !== "string" || d.method.length > 64) return null;
  if (!Array.isArray(d.params)) return null;
  return { channel: CHANNEL, kind: "req", id: d.id, method: d.method, params: d.params };
}

// ─── Origin ───────────────────────────────────────────────────────────────────

/**
 * What the background learned about the sender from the browser itself.
 *
 * `frameId` is here because a page can embed anything. An iframe on
 * `evil.example` inside `dex.example` sends messages that arrive with the
 * *frame's* own origin — the browser is honest about that — but a user reading
 * an approval dialog sees the address bar, which says `dex.example`. Rather
 * than try to describe that situation in a sentence a person can act on, the
 * top frame is the only one that may ask.
 */
export type SenderFacts = { origin?: string; frameId?: number };

/**
 * Decide the origin to attribute this request to, or refuse.
 *
 * Refusing is not a fallback here — it is most of the job. An origin that is
 * absent, opaque (`"null"`, which is what a sandboxed frame or a `data:` URL
 * reports), or not `https:` gets no answer, because none of those can be shown
 * to a person as "the site asking for your signature".
 *
 * `http://localhost` is the one exception, and it is for the person developing
 * against this wallet. It is not a general `http:` exception: a plaintext
 * origin on the open network can be rewritten in flight by anyone between the
 * user and the server, so a grant to one is a grant to whoever is on the path.
 */
export function originOf(sender: SenderFacts): { origin: string } | { error: ApiError } {
  if (sender.frameId !== undefined && sender.frameId !== 0) {
    return { error: refused("Only the top frame of a page may talk to this wallet.") };
  }
  const raw = sender.origin;
  if (typeof raw !== "string" || raw.length === 0 || raw === "null") {
    return { error: refused("This page has no origin the wallet can show you.") };
  }
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    return { error: refused("This page has no origin the wallet can show you.") };
  }
  if (url.protocol === "https:") return { origin: url.origin };
  if (url.protocol === "http:" && isLoopback(url.hostname)) return { origin: url.origin };
  return { error: refused(`This wallet only talks to https sites (got ${url.protocol}).`) };
}

function isLoopback(host: string): boolean {
  return host === "localhost" || host === "127.0.0.1" || host === "[::1]" || host === "::1";
}

/**
 * How an origin is shown to the person deciding.
 *
 * Always the host, never a title the page chose for itself, and never
 * truncated in the middle — `pay.bank.example…` and `pay.bank.example.evil.tld`
 * differ only past the point a truncation would cut, which is precisely where
 * an attacker puts the difference.
 */
export function displayOrigin(origin: string): string {
  try {
    const u = new URL(origin);
    return u.port ? `${u.hostname}:${u.port}` : u.hostname;
  } catch {
    return origin;
  }
}

/**
 * The port name a wallet window uses to tell the background "I am the signer
 * for this origin".
 *
 * It lives here rather than in the worker so the window can import it without
 * importing the worker — a page that pulled in the service worker's module
 * would pull in its `chrome.windows` and `chrome.storage.session` calls too,
 * and neither belongs in a page.
 */
export const WALLET_PORT = "phoenix-wallet-window";
